import Image from "next/image";

// Official BIO:ON INSIGHT logos (transparent, generated by scripts/prepare-logos.ps1).
export function Wordmark({ className = "h-11 w-auto" }: { className?: string }) {
  return (
    <Image src="/brand/logo-horizontal.png" alt="BIO:ON Insight" width={640} height={274} priority className={className} />
  );
}

export function VerticalLogo({ className = "h-40 w-auto" }: { className?: string }) {
  return <Image src="/brand/logo-vertical.png" alt="BIO:ON Insight" width={480} height={686} className={className} />;
}
