import Image from "next/image";

// Official BIO:ON INSIGHT logos (transparent, generated by scripts/prepare-logos.ps1).
export function Wordmark({ className = "h-11 w-auto" }: { className?: string }) {
  return (
    // The logo is navy on transparent, so in dark mode it sits on a light pill to stay legible.
    <Image
      src="/brand/logo-horizontal.png"
      alt="BIO:ON Insight"
      width={640}
      height={274}
      preload
      className={`${className} dark:rounded-lg dark:bg-white dark:px-1.5 dark:py-0.5`}
    />
  );
}

export function VerticalLogo({ className = "h-40 w-auto" }: { className?: string }) {
  return (
    <Image
      src="/brand/logo-vertical.png"
      alt="BIO:ON Insight"
      width={480}
      height={686}
      className={`${className} dark:rounded-2xl dark:bg-white dark:p-3`}
    />
  );
}
